version: '3.9'

services:


  userservice-db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: GBC_EventBooking
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/users:/var/lib/postgresql/data
      - ./init/postgres/users/init.sql:/init.sql



  pgadmin:
     image: dpage/pgadmin4
     ports:
       - "8888:80"
     container_name: pgadmin
     environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
