version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - booking-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - booking-network

  booking-service:
    build:
      context: ./BookingService  # Adjust the context to point to the BookingService directory
      dockerfile: Dockerfile
    ports:
      - "2011:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo:27017/booking-service  # MongoDB connection string
    depends_on:
      - mongo
    networks:
      - booking-network


